PORTNAME=   neon-world-os
DISTVERSION=220.0.0
CATEGORIES= sysutils
MAINTAINER= maintainers@example.invalid
COMMENT=    Host-embedded OS simulator (C++)
LICENSE=    MIT
USES=       cmake compiler:c++20-lang
USE_GITHUB= yes
GH_ACCOUNT= your
GH_PROJECT= repo

PLIST_FILES= bin/neon
