repos:
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks: [{id: codespell
      args: ["-w","--ignore-words=.codespell-ignore-words.txt"], args: ["-w"], additional_dependencies: ["tomli"]}]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks: [{id: clang-format}]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks: [{id: markdownlint}]
