blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/your/repo/security/policy
    about: Please report security vulnerabilities privately as described in SECURITY.md
