
#!/usr/bin/env python3
import os, glob, pathlib
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
hdrs = glob.glob(os.path.join(ROOT, "include", "neon", "*.hpp"))
OUTDIR = os.path.join(ROOT, "tests", "headers")
os.makedirs(OUTDIR, exist_ok=True)
for h in hdrs:
    name = pathlib.Path(h).name.replace(".hpp","")
    with open(os.path.join(OUTDIR, f"{name}.cpp"), "w") as f:
        f.write("// AUTOGENERATED. SPDX-License-Identifier: MIT\n")
        f.write('#include "neon/%s.hpp"\n' % name if name not in ("neon","common") else '#include "neon/%s.hpp"\n' % name)
print(OUTDIR)
