name: actionlint
on: [push, pull_request]
permissions: { contents: read }
jobs:
  lint:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v1