name: clang-format check
on: [push, pull_request]
permissions: { contents: read }
jobs:
  format:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Run clang-format -n
        run: |
          files=$(git ls-files '*.[ch]' '*.[ch]pp' '*.cc' '*.hh' || true)
          if [ -n "$files" ]; then clang-format -n $files || true; fi