name: commitlint
on: [pull_request]
permissions: { contents: read }
jobs:
  commitlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5