name: Compile flags audit
on: [push, pull_request]
permissions: { contents: read }
jobs:
  audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - run: cmake --build build -j
      - run: python3 tools/compile_flags_audit.py build