name: Container (multi-arch, sign)
on:
  push:
    branches: [ main ]
jobs:
  buildx:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions: { contents: read, packages: write, id-token: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push multi-arch
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packaging/docker/Dockerfile.distroless
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/neon:latest
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Sign image (keyless)
        env: { COSIGN_EXPERIMENTAL: "1" }
        run: cosign sign --yes ghcr.io/${{ github.repository }}/neon:latest