name: Cppcheck
on: [push, pull_request]
permissions: { contents: read }
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --quiet --suppress=missingIncludeSystem . || true