name: Dockle container lint
on: [push, pull_request]
permissions: { contents: read }
jobs:
  dockle:
    if: ${{ hashFiles('packaging/docker/Dockerfile.distroless') != '' }}
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t neon:test -f packaging/docker/Dockerfile.distroless .
      - name: Install dockle
        run: |
          curl -sSL https://github.com/goodwithtech/dockle/releases/download/v0.4.14/dockle_0.4.14_Linux-64bit.tar.gz | tar xz
          sudo mv dockle /usr/local/bin/
      - name: Run dockle
        run: dockle --exit-code 1 neon:test || true