name: Docs
on: { push: { branches: [ main ] } }
jobs:
  doxygen:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
      - name: Generate docs
        run: doxygen docs/api/Doxyfile
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: docs/html }
  deploy:
    needs: doxygen
    permissions: { pages: write, id-token: write }
    environment: { name: github-pages }
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4