
name: Doxygen (artifact)
on: [push, pull_request]
permissions: { contents: read }
jobs:
  doxygen:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
      - name: Build docs
        run: doxygen docs/api/Doxyfile || true
      - uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: build/docs/html
          if-no-files-found: ignore