name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions: { contents: read }
jobs:
  label:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml