
name: Link Check
on: [pull_request]
permissions: { contents: read }
jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --accept 200,204 --exclude-mail -- ../**/*.md