name: Link check
on: [push, pull_request]
permissions: { contents: read }
jobs:
  links:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress **/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}