name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '33 3 * * 3'
  push: { branches: [ main ] }
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  id-token: write
jobs:
  analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif