name: pre-commit autoupdate
on:
  schedule:
    - cron: '11 4 * * 2'
  workflow_dispatch:
permissions: { contents: read }
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Autoupdate hooks
        run: pre-commit autoupdate || true