name: Release Drafter
on:
  push: { branches: [ main ] }
permissions: { contents: read }
jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: release-drafter/release-drafter@v6
        env: { GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }