
name: Release (build, attest)
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build-attest:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: read
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR="ZIP;TGZ"
      - name: Build
        run: cmake --build build -j
      - name: Package
        run: cmake --build build --target package
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip, build/*.tar.gz
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "build/*.zip"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.7.0
      - name: Generate checksums
        run: |
          cd build
          sha256sum *.zip *.tar.gz > SHA256SUMS.txt
      - name: Sign artifacts (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cd build
          for f in *.zip *.tar.gz; do
            cosign sign-blob --yes --output-signature "$f.sig" "$f"
          done
      - name: Upload signatures
        uses: softprops/action-gh-release@v2
        with:
          files: build/SHA256SUMS.txt, build/*.sig