
name: SBOM (source) artifact
on: [push, pull_request]
permissions: { contents: read }
jobs:
  sbom:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM
        run: python3 tools/sbom/generate.py
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-source
          path: sbom/source.cdx.json