name: CodeQL
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  schedule: [ { cron: '0 3 * * 1' } ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions: { actions: read, contents: read, security-events: write }
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with: { languages: cpp }
      - uses: github/codeql-action/analyze@v3