name: shellcheck
on: [push, pull_request]
permissions: { contents: read }
jobs:
  shlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck -S warning $(git ls-files '*.sh') || true