
name: Size Budget
on: [pull_request]
permissions: { contents: read }
jobs:
  size:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j
      - name: Enforce size budget (<= 6MB for neon)
        run: |
          sz=$(stat -c%s "build/bin/neon" || stat -f%z "build/bin/neon")
          echo "neon size: $sz bytes"
          [ "$sz" -le 6291456 ]