name: SLSA provenance
on:
  push:
    tags: ['v*.*.*']
jobs:
  generate-provenance:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      actions: read
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: slsa-framework/slsa-github-generator/actions/generator@v2.0.0
        with:
          build-artifact-path: build
          compile-generator: true