name: Trivy
on: [push, pull_request]
permissions: { contents: read }
jobs:
  fs-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with: { scan-type: 'fs', format: 'table', exit-code: '1', ignore-unfixed: true, vuln-type: 'os,library' }
  image-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t neon:test -f packaging/docker/Dockerfile .
      - uses: aquasecurity/trivy-action@0.28.0
        with: { image-ref: 'neon:test', format: 'table', exit-code: '1', ignore-unfixed: true }