name: Valgrind
on: [push, pull_request]
permissions: { contents: read }
jobs:
  memcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Build (RelWithDebInfo)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build -j
      - name: Self-test under Valgrind
        run: |
          valgrind --error-exitcode=1 ./build/apps/neon --self-test