
name: Build Python wheels
on:
  push: { branches: [ main ] }
  workflow_dispatch:
permissions: { contents: read }
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Build wheel
        run: |
          pip install build scikit-build-core pybind11
          cd bindings/python
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: bindings/python/dist/*.whl
      - name: Test import
        run: |
          pip install bindings/python/dist/*.whl
          python -c "import neonpy; v=neonpy.Vfs(); v.touch('/a'); print('ok')"