name: yamllint
on: [push, pull_request]
permissions: { contents: read }
jobs:
  yaml:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint -s . || true